# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('seguimiento', 'SEGUIMIENTO'), ('revisión', 'REVISION'), ('fuera_de_servicio', 'FUERA DE SERVICIO'), ('cambio_placa', 'CAMBIO PLACA')], default='ok', max_length=120)),
                ('enObservacion', models.BooleanField(default=False)),
                ('pdv', models.CharField(choices=[('calle104', 'CALLE 104'), ('calle93', 'CALLE 93'), ('calle72', 'CALLE 72')], default='104', max_length=120)),
                ('ubicacion', models.CharField(choices=[('bar', 'BAR'), ('baño', 'BAÑO'), ('bodega', 'BODEGA'), ('comedor', 'COMEDOR'), ('cuarto_de_aseo', 'CUARTO DE ASEO'), ('dulce', 'DULCE'), ('ensamble', 'ENSAMBLE'), ('granoleria', 'GRANOLERIA'), ('locker', 'LOCKER'), ('oficina', 'OFICINA'), ('plancha', 'PLANCHA'), ('produccion', 'PRODUCCION'), ('punto', 'PUNTO'), ('stewart', 'STEWART'), ('sotano', 'SOTANO')], default='ok', max_length=120)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('serie', models.CharField(blank=True, max_length=120)),
                ('placa', models.CharField(blank=True, max_length=120)),
                ('propio', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('vidautil', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor')),
            ],
        ),
    ]
