# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-04 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.CharField(choices=[('bar', 'BAR'), ('baño', 'BAÑO'), ('bodega', 'BODEGA'), ('comedor', 'COMEDOR'), ('cuarto_de_aseo', 'CUARTO DE ASEO'), ('dulce', 'DULCE'), ('ensamble', 'ENSAMBLE'), ('granoleria', 'GRANOLERIA'), ('locker', 'LOCKER'), ('oficina', 'OFICINA'), ('panaderia', 'PANADERIA'), ('plancha', 'PLANCHA'), ('produccion', 'PRODUCCION'), ('punto', 'PUNTO'), ('stewart', 'STEWART'), ('sótano', 'SOTANO')], default='ok', max_length=120),
        ),
    ]
