# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190104_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='pdv',
            field=models.CharField(choices=[('calle 104', 'CALLE 104'), ('calle 93', 'CALLE 93'), ('calle 72', 'CALLE 72')], default='104', max_length=120),
        ),
    ]
