# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-16 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_auto_20190104_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperacion',
            name='mantenimiento',
            field=models.CharField(choices=[('correctivo', 'Correctivo'), ('preventivo', 'Preventivo'), ('compra', 'Compra')], default='correctivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='mantenimiento',
            field=models.CharField(choices=[('correctivo', 'Correctivo'), ('preventivo', 'Preventivo'), ('compra', 'Compra')], default='correctivo', max_length=50),
        ),
    ]
